---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  environment:
  working_directory: ~/project

version: 2
jobs:
  check-build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Check the project builds
          command: yarn run build
  python-lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install flake8
      - run:
          name: Lint webapp with Flake8
          command: yarn run python-lint
  scss-lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint scss with sass-lint
          command: yarn run lint-scss
  python-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Run tests
          command: python3 -m unittest discover tests
workflows:
  version: 2
  build:
    jobs:
      - check-build
      - python-lint
      - scss-lint
      - python-tests
